title: Oleksandr Kosovan # your name (or website title) here
logo: "/images/profile.JPG?raw=true" # your photo (or logo) here
description: >
  <p align="center">
  <a href="https://www.linkedin.com/in/kosovan-oleksandr/">LinkedIn</a> |
  <a href="https://github.com/OleksandrKosovan">GitHub</a> 
  </p>
  
  <p align="justify">
  I am Data Scientist / Machine Learning Engineer
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-E852QYSYP2
